package pkg007_ejercicioobligatorio2;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.JOptionPane;

public class AddPassengerForm extends javax.swing.JFrame {
    
    final String JDBC_DRIVER = "com.mysql.jdbc.Driver";
    final String DB_URL = "jdbc:mysql://localhost/aeropuerto";
    final String USER = "root";
    final String PASS = "";

    // Atributos variables
    Connection connection = null;
    PreparedStatement preparedStatement = null;
    ResultSet resultSet = null;
    
    public AddPassengerForm() {
        initComponents();
        buttonGroup1.add(maleRb);
        buttonGroup1.add(femaleRb);
    }
    
    public Connection conecta() {
        Connection con = null;
        try {
            Class.forName(JDBC_DRIVER);
            con = (com.mysql.jdbc.Connection) DriverManager.getConnection(DB_URL, USER, PASS);
        } catch (SQLException se) {
            se.printStackTrace();
        } catch (Exception e) {
            e.printStackTrace();
        }
        return con;
    }
    
    
    private void cleanTextFields() {
        dniTf.setText("");
        flightIdSpinner.setValue(0);
        nameTf.setText("");
        surnameTf.setText("");
        surname2Tf.setText("");
        nationalityTf.setText("");
        ageSpinner.setValue(0);
        maleRb.setSelected(false);
        femaleRb.setSelected(false);
    }
    
    private String getSelectedGender() {
        if (maleRb.isSelected()){
            return "H";
        } else if (femaleRb.isSelected()) {
            return "M";
        }
        return null;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        selectBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        insertBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nameTf = new javax.swing.JTextField();
        surnameTf = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        dniTf = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        surname2Tf = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        nationalityTf = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        ageSpinner = new javax.swing.JSpinner();
        maleRb = new javax.swing.JRadioButton();
        femaleRb = new javax.swing.JRadioButton();
        flightIdSpinner = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Pasajero");

        jLabel2.setText("idVuelo");

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        selectBtn.setText("Seleccionar");
        selectBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectBtnActionPerformed(evt);
            }
        });

        updateBtn.setText("Actualizar");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        insertBtn.setText("Insertar");
        insertBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertBtnActionPerformed(evt);
            }
        });

        deleteBtn.setText("Eliminar");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(selectBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(updateBtn)
                        .addGap(18, 18, 18)
                        .addComponent(insertBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(deleteBtn)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateBtn)
                    .addComponent(insertBtn)
                    .addComponent(deleteBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(selectBtn)
                .addContainerGap())
        );

        jLabel3.setText("Nombre");

        jLabel4.setText("Apellido");

        jLabel5.setText("dni");

        jLabel6.setText("Apellido 2");

        jLabel7.setText("Nacionalidad");

        jLabel8.setText("Edad");

        jLabel9.setText("Sexo");

        ageSpinner.setModel(new javax.swing.SpinnerNumberModel(1, 0, 120, 1));

        maleRb.setText("M");

        femaleRb.setText("F");

        flightIdSpinner.setModel(new javax.swing.SpinnerNumberModel(1, 0, 120, 1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(surnameTf)
                            .addComponent(surname2Tf)
                            .addComponent(nationalityTf)
                            .addComponent(ageSpinner, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(maleRb, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 160, Short.MAX_VALUE)
                                .addComponent(femaleRb, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(dniTf)
                            .addComponent(nameTf)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(flightIdSpinner)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(dniTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(flightIdSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nameTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(surnameTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(surname2Tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(nationalityTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(ageSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(maleRb)
                    .addComponent(femaleRb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
         try {
            connection = conecta();
            String query = "update pasajeros set  nombre = ?, apellido1 = ?, "
                    + "apellido2 = ?, nacionalidad = ?, edad = ?, sexo = ? where dni = ? AND idVuelo = ?";
         
            preparedStatement = connection.prepareStatement(query);
    
            preparedStatement.setString(1, nameTf.getText());
            preparedStatement.setString(2, surnameTf.getText());
            preparedStatement.setString(3, surname2Tf.getText());
            preparedStatement.setString(4, nationalityTf.getText());
            preparedStatement.setInt(5, (int) ageSpinner.getValue());
            preparedStatement.setString(6, getSelectedGender());
            
            preparedStatement.setString(7, dniTf.getText());
            preparedStatement.setInt(8, (int) flightIdSpinner.getValue());  
            // Ejecuto la consulta
            int resultado = preparedStatement.executeUpdate();
            if (resultado > 0) {
                JOptionPane.showMessageDialog(this, "Registro actualizado correctamente");
            } else {
                JOptionPane.showMessageDialog(this, "Error al actualizar");
            }

            connection.close();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al actualizar");
        }

        cleanTextFields();
    }//GEN-LAST:event_updateBtnActionPerformed

    private void insertBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertBtnActionPerformed
        try {
            connection = conecta();
            String query = "insert into pasajeros (dni, idVuelo, nombre, apellido1, apellido2, nacionalidad, edad, sexo) "
                    + "values (?,?,?,?,?,?,?,?)";
            preparedStatement = connection.prepareStatement(query);
            preparedStatement.setString(1, dniTf.getText()); 
            preparedStatement.setInt(2, (int) flightIdSpinner.getValue());  
            preparedStatement.setString(3, nameTf.getText());
            preparedStatement.setString(4, surnameTf.getText());
            preparedStatement.setString(5, surname2Tf.getText());
            preparedStatement.setString(6, nationalityTf.getText());
            preparedStatement.setInt(7, (int) ageSpinner.getValue());
            preparedStatement.setString(8, getSelectedGender());
            

            System.out.println(preparedStatement.toString());
            // Ejecuto la consulta
            int resultado = preparedStatement.executeUpdate();
            System.out.println(resultado);
            if (resultado > 0) {
                JOptionPane.showMessageDialog(this, "Registro insertado correctamente");
            } else {
                JOptionPane.showMessageDialog(this, "Error al insertar");
            }

            connection.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error al insertar");
        }

        cleanTextFields();
    }//GEN-LAST:event_insertBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        try {
            connection = conecta();
            String query = "delete from pasajeros where DNI = ? AND Idvuelo = ?";
            preparedStatement = connection.prepareStatement(query);
            preparedStatement.setString(1, dniTf.getText());
            preparedStatement.setInt(2, (int) flightIdSpinner.getValue());   
            System.out.println(preparedStatement);

            int resultado = preparedStatement.executeUpdate();
            if (resultado > 0) {
                JOptionPane.showMessageDialog(this, "Registro borrado correctamente");
            } else {
                JOptionPane.showMessageDialog(this, "Error al borrar");
            }

            connection.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error al borrar");
        }

        cleanTextFields();
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void selectBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectBtnActionPerformed
        try {
            connection = conecta();

            String query = "Select * from pasajeros where nombre like ? order by nombre";
            preparedStatement = connection.prepareStatement(query, ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
 
            ;
            preparedStatement.setString(1, "%"+nameTf.getText().trim()+"%"); 

            // Ejecuto la consulta
            resultSet = preparedStatement.executeQuery();
            if (resultSet.next()) {
                String[][] resultTable = generateResultTable();
                new ShowSelect(resultTable).setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "No se ha encontrado ninguna persona");
            }

            connection.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error al seleccionar");
        }
        
        cleanTextFields();
    }//GEN-LAST:event_selectBtnActionPerformed
    
    private String[][] generateResultTable() throws SQLException {
        ResultSetMetaData meta = resultSet.getMetaData();
        int columns = meta.getColumnCount();
        resultSet.last();
        int rows = resultSet.getRow();
        String[][] table = new String[rows + 1][columns];

        for (int i = 0; i < columns; i++) {
            table[0][i] = meta.getColumnName(i + 1) + "[" + meta.getColumnTypeName(i + 1) + "]";
        }
        
        resultSet.beforeFirst();
        int i = 1;
        while (resultSet.next()) {
            for (int j = 0; j < table[i].length; j++) {
                if (resultSet.getObject(j + 1) == null)
                    table[i][j] = "null";
                else
                    table[i][j] = resultSet.getObject(j + 1).toString();
            }
            i++;
        }
        return table;
    }
       
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner ageSpinner;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JTextField dniTf;
    private javax.swing.JRadioButton femaleRb;
    private javax.swing.JSpinner flightIdSpinner;
    private javax.swing.JButton insertBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton maleRb;
    private javax.swing.JTextField nameTf;
    private javax.swing.JTextField nationalityTf;
    private javax.swing.JButton selectBtn;
    private javax.swing.JTextField surname2Tf;
    private javax.swing.JTextField surnameTf;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables

}
